import PDFDocument from "pdfkit";

export function createAppointmentReceipt(appointment) {
  const doc = new PDFDocument({ size: "A4", margin: 48 });
  const chunks = [];

  doc.on("data", (chunk) => chunks.push(chunk));

  doc.fontSize(20).text("Legal and Field Consultancy Firms", { align: "center" });
  doc.moveDown(0.5);
  doc.fontSize(14).text("Appointment Receipt", { align: "center" });
  doc.moveDown(2);
  doc.fontSize(10).text(`Reference: ${appointment.id}`);
  doc.text(`Client: ${appointment.client?.name || "Client"}`);
  doc.text(`Lawyer: ${appointment.lawyer?.user?.name || "Pending assignment"}`);
  doc.text(`Consultation: ${appointment.consultationType}`);
  doc.text(`Priority: ${appointment.priority}`);
  doc.text(`Status: ${appointment.status}`);
  doc.text(`Preferred Start: ${appointment.preferredStart}`);
  doc.text(`Scheduled Start: ${appointment.scheduledStart || "Pending"}`);
  doc.moveDown();
  doc.text("This receipt was generated by the LFC appointment platform and may be used for client tracking.");
  doc.end();

  return new Promise((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
}
